"""create entity and edge tables

Revision ID: 2cdae4194444
Revises: 
Create Date: 2026-09-07 22:09:25.454930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cdae4194444'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('abstract_work',
    sa.Column('designation', sa.Text(), nullable=True),
    sa.Column('title_name_chi', sa.Text(), nullable=True),
    sa.Column('title_name_kor', sa.Text(), nullable=True),
    sa.Column('title_name_alter', sa.Text(), nullable=True),
    sa.Column('pb_edition_status', sa.String(length=16), nullable=True),
    sa.Column('hangul_edition_status', sa.String(length=16), nullable=True),
    sa.Column('numbered_sections_status', sa.String(length=16), nullable=True),
    sa.Column('contents_type', sa.String(length=64), nullable=True),
    sa.Column('creation_period', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('allusion',
    sa.Column('citation_type', sa.String(length=64), nullable=True),
    sa.Column('title_chi', sa.Text(), nullable=True),
    sa.Column('title_kor', sa.Text(), nullable=True),
    sa.Column('work_chi', sa.Text(), nullable=True),
    sa.Column('work_kor', sa.Text(), nullable=True),
    sa.Column('allusion_type', sa.String(length=64), nullable=True),
    sa.Column('explain', sa.Text(), nullable=True),
    sa.Column('original_text', sa.Text(), nullable=True),
    sa.Column('translation', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('source_work', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('background_e',
    sa.Column('nation_eng', sa.Text(), nullable=True),
    sa.Column('nation_kor', sa.Text(), nullable=True),
    sa.Column('dynasty_chi', sa.Text(), nullable=True),
    sa.Column('dynasty_kor', sa.Text(), nullable=True),
    sa.Column('ruler_chi', sa.Text(), nullable=True),
    sa.Column('ruler_kor', sa.Text(), nullable=True),
    sa.Column('historicity', sa.String(length=16), nullable=True),
    sa.Column('source_work', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('background_l',
    sa.Column('stage_type', sa.String(length=64), nullable=True),
    sa.Column('nation_chi', sa.Text(), nullable=True),
    sa.Column('nation_kor', sa.Text(), nullable=True),
    sa.Column('nation_eng', sa.Text(), nullable=True),
    sa.Column('province_chi', sa.Text(), nullable=True),
    sa.Column('province_kor', sa.Text(), nullable=True),
    sa.Column('landmark_chi', sa.Text(), nullable=True),
    sa.Column('landmark_kor', sa.Text(), nullable=True),
    sa.Column('latitude', sa.String(length=64), nullable=True),
    sa.Column('longitude', sa.String(length=64), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('background_w',
    sa.Column('stage_type', sa.String(length=64), nullable=True),
    sa.Column('whereabouts_chi', sa.Text(), nullable=True),
    sa.Column('whereabouts_kor', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('book',
    sa.Column('designation', sa.Text(), nullable=True),
    sa.Column('cover_name_chi', sa.Text(), nullable=True),
    sa.Column('cover_name_kor', sa.Text(), nullable=True),
    sa.Column('title_name_chi', sa.Text(), nullable=True),
    sa.Column('title_name_kor', sa.Text(), nullable=True),
    sa.Column('division', sa.String(length=16), nullable=True),
    sa.Column('institution_kor', sa.Text(), nullable=True),
    sa.Column('institution_chi', sa.Text(), nullable=True),
    sa.Column('setting_type', sa.String(length=64), nullable=True),
    sa.Column('volume_type', sa.String(length=16), nullable=True),
    sa.Column('etc', sa.Text(), nullable=True),
    sa.Column('pb_edition_status', sa.String(length=16), nullable=True),
    sa.Column('contents_type', sa.String(length=32), nullable=True),
    sa.Column('contents_information', sa.Text(), nullable=True),
    sa.Column('date_statement', sa.Text(), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('caste',
    sa.Column('f_classification', sa.Text(), nullable=True),
    sa.Column('s_classification', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ch_elements',
    sa.Column('gender', sa.String(length=32), nullable=True),
    sa.Column('existence', sa.String(length=32), nullable=True),
    sa.Column('facticity', sa.String(length=32), nullable=True),
    sa.Column('type', sa.String(length=64), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('character',
    sa.Column('work_kor', sa.Text(), nullable=True),
    sa.Column('work_chi', sa.Text(), nullable=True),
    sa.Column('ch_name_kor', sa.Text(), nullable=True),
    sa.Column('ch_name_chi', sa.Text(), nullable=True),
    sa.Column('nickname', sa.Text(), nullable=True),
    sa.Column('primary_classification', sa.Text(), nullable=True),
    sa.Column('secondary_classification', sa.Text(), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('gender', sa.String(length=32), nullable=True),
    sa.Column('existence', sa.String(length=32), nullable=True),
    sa.Column('facticity', sa.String(length=32), nullable=True),
    sa.Column('attribute_type', sa.String(length=64), nullable=True),
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comment',
    sa.Column('c_type', sa.String(length=64), nullable=True),
    sa.Column('work_kor', sa.Text(), nullable=True),
    sa.Column('work_chi', sa.Text(), nullable=True),
    sa.Column('target_book', sa.Text(), nullable=True),
    sa.Column('original_text', sa.Text(), nullable=True),
    sa.Column('translation', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('edge',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_class', sa.String(length=64), nullable=False),
    sa.Column('source_id', sa.String(length=128), nullable=False),
    sa.Column('source_name', sa.Text(), nullable=True),
    sa.Column('target_class', sa.String(length=64), nullable=False),
    sa.Column('target_id', sa.String(length=128), nullable=False),
    sa.Column('target_name', sa.Text(), nullable=True),
    sa.Column('relation', sa.String(length=64), nullable=True),
    sa.Column('etc1', sa.Text(), nullable=True),
    sa.Column('etc2', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_class', 'source_id', 'target_class', 'target_id', 'relation', name='uq_edge_connection')
    )
    op.create_index('ix_edge_relation', 'edge', ['relation'], unique=False)
    op.create_index('ix_edge_source', 'edge', ['source_class', 'source_id'], unique=False)
    op.create_index('ix_edge_target', 'edge', ['target_class', 'target_id'], unique=False)
    op.create_table('embedded_work',
    sa.Column('work_kor', sa.Text(), nullable=True),
    sa.Column('work_chi', sa.Text(), nullable=True),
    sa.Column('ew_title', sa.Text(), nullable=True),
    sa.Column('ew_type', sa.String(length=64), nullable=True),
    sa.Column('ew_genre', sa.String(length=64), nullable=True),
    sa.Column('language', sa.String(length=32), nullable=True),
    sa.Column('original_text', sa.Text(), nullable=True),
    sa.Column('translation', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('episode',
    sa.Column('t_title', sa.Text(), nullable=True),
    sa.Column('target_book', sa.Text(), nullable=True),
    sa.Column('line_count', sa.String(length=32), nullable=True),
    sa.Column('word_count', sa.String(length=32), nullable=True),
    sa.Column('episode', sa.String(length=32), nullable=True),
    sa.Column('original_text', sa.Text(), nullable=True),
    sa.Column('translation', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('number',
    sa.Column('n_title', sa.Text(), nullable=True),
    sa.Column('target_book', sa.Text(), nullable=True),
    sa.Column('con_type', sa.String(length=64), nullable=True),
    sa.Column('con_information', sa.Text(), nullable=True),
    sa.Column('line_count', sa.String(length=32), nullable=True),
    sa.Column('word_count', sa.String(length=32), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('participant',
    sa.Column('role_type', sa.String(length=64), nullable=True),
    sa.Column('unknown_status', sa.String(length=64), nullable=True),
    sa.Column('name_chi', sa.Text(), nullable=True),
    sa.Column('name_kor', sa.Text(), nullable=True),
    sa.Column('nationality', sa.Text(), nullable=True),
    sa.Column('birth_year', sa.String(length=32), nullable=True),
    sa.Column('death_year', sa.String(length=32), nullable=True),
    sa.Column('courtesy_name', sa.Text(), nullable=True),
    sa.Column('pen_name', sa.Text(), nullable=True),
    sa.Column('related_works', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('related_work',
    sa.Column('work_kor', sa.Text(), nullable=True),
    sa.Column('work_chi', sa.Text(), nullable=True),
    sa.Column('writer', sa.Text(), nullable=True),
    sa.Column('record', sa.Text(), nullable=True),
    sa.Column('rw_title', sa.Text(), nullable=True),
    sa.Column('name_kor', sa.Text(), nullable=True),
    sa.Column('name_chi', sa.Text(), nullable=True),
    sa.Column('genre', sa.String(length=64), nullable=True),
    sa.Column('language', sa.String(length=32), nullable=True),
    sa.Column('original_text', sa.Text(), nullable=True),
    sa.Column('translation', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('remark',
    sa.Column('type', sa.String(length=64), nullable=True),
    sa.Column('reviewer', sa.Text(), nullable=True),
    sa.Column('work_kor', sa.Text(), nullable=True),
    sa.Column('work_chi', sa.Text(), nullable=True),
    sa.Column('target_book', sa.Text(), nullable=True),
    sa.Column('original_text', sa.Text(), nullable=True),
    sa.Column('translation', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('review',
    sa.Column('work_kor', sa.Text(), nullable=True),
    sa.Column('work_chi', sa.Text(), nullable=True),
    sa.Column('target_book', sa.Text(), nullable=True),
    sa.Column('reviewer', sa.Text(), nullable=True),
    sa.Column('criticism_type', sa.String(length=64), nullable=True),
    sa.Column('paratext_title', sa.Text(), nullable=True),
    sa.Column('language', sa.String(length=32), nullable=True),
    sa.Column('original_text', sa.Text(), nullable=True),
    sa.Column('translation', sa.Text(), nullable=True),
    sa.Column('mentioned_work', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scene',
    sa.Column('work_kor', sa.Text(), nullable=True),
    sa.Column('work_chi', sa.Text(), nullable=True),
    sa.Column('viewpoint', sa.String(length=32), nullable=True),
    sa.Column('language', sa.String(length=32), nullable=True),
    sa.Column('original_text', sa.Text(), nullable=True),
    sa.Column('translation', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('temporal_background', sa.Text(), nullable=True),
    sa.Column('spatial_background_1', sa.Text(), nullable=True),
    sa.Column('spatial_background_2', sa.Text(), nullable=True),
    sa.Column('place_background', sa.Text(), nullable=True),
    sa.Column('characters', sa.Text(), nullable=True),
    sa.Column('allusions', sa.Text(), nullable=True),
    sa.Column('spatial_background_link', sa.Text(), nullable=True),
    sa.Column('place_background_link', sa.Text(), nullable=True),
    sa.Column('character_link', sa.Text(), nullable=True),
    sa.Column('allusion_link', sa.Text(), nullable=True),
    sa.Column('embedded_work_status', sa.String(length=16), nullable=True),
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('side_dot',
    sa.Column('n_title', sa.Text(), nullable=True),
    sa.Column('target_book', sa.Text(), nullable=True),
    sa.Column('original_text', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('works_compilation',
    sa.Column('type', sa.String(length=32), nullable=True),
    sa.Column('designation', sa.Text(), nullable=True),
    sa.Column('cover_name_chi', sa.Text(), nullable=True),
    sa.Column('cover_name_kor', sa.Text(), nullable=True),
    sa.Column('title_name_chi', sa.Text(), nullable=True),
    sa.Column('title_name_kor', sa.Text(), nullable=True),
    sa.Column('division', sa.String(length=16), nullable=True),
    sa.Column('institution_kor', sa.Text(), nullable=True),
    sa.Column('institution_chi', sa.Text(), nullable=True),
    sa.Column('setting_type', sa.String(length=64), nullable=True),
    sa.Column('included_work', sa.Text(), nullable=True),
    sa.Column('etc', sa.Text(), nullable=True),
    sa.Column('published_year', sa.Text(), nullable=True),
    sa.Column('related_discussion', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('works_compilation')
    op.drop_table('side_dot')
    op.drop_table('scene')
    op.drop_table('review')
    op.drop_table('remark')
    op.drop_table('related_work')
    op.drop_table('participant')
    op.drop_table('number')
    op.drop_table('episode')
    op.drop_table('embedded_work')
    op.drop_index('ix_edge_target', table_name='edge')
    op.drop_index('ix_edge_source', table_name='edge')
    op.drop_index('ix_edge_relation', table_name='edge')
    op.drop_table('edge')
    op.drop_table('comment')
    op.drop_table('character')
    op.drop_table('ch_elements')
    op.drop_table('caste')
    op.drop_table('book')
    op.drop_table('background_w')
    op.drop_table('background_l')
    op.drop_table('background_e')
    op.drop_table('allusion')
    op.drop_table('abstract_work')
    # ### end Alembic commands ###
